language: r
r:
  - oldrel
  - release

os:
  - linux
  - osx
  
before-install:
  - tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet
  - sudo tlmgr install texlive-fonts-extra
  - sudo tlmgr install titling framed inconsolata